### ISSUE TITLE
Configure remote upload into any plataform.

### ISSUE THREAD

**Issue by Francisco-Fetapi** [edito13/Sapunga_back_end#1]
At the time, the project only allows saving files into the server filesystem. This is not the best way to _persist files_. Most of the time, a lot of applications connect their backend with a service that provides an easy way to persist files.

I highly recommend using [firebase storage](https://firebase.google.com/docs/storage?hl=pt-br).

**Comment by edito13** [comment]
Thanks to you, we could solve it by using [Firebase Storage](https://firebase.google.com/docs/storage?hl=pt-br).
